config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  get 'signup' => 'users#new'
  resources :users, :points

  #Nested Route - Activities/Points
  resources :activities do
 	  resources :points
  end

  #LOGIN
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #Experimental Graph D3
  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
end

app/views/pages/index.html.erb
<div class="home">

	<h1>WELCOME TO KARMA POLICE!</h1>
	<p>- a peer based feedback system</p>
	
	<hr>
	<div class="slider">
    	<div><%= image_tag('https://ubuntugnome.org/wp-content/uploads/668c/feedback_vp.jpg') %></div>
    	<div><%= image_tag('https://media3.giphy.com/media/1PmRU7Jj5U88/200_s.gif') %></div>
    	<div>
    		<h3>NEWS</h3>
	  		<p>New things coming?!</p>
	  		<p>Teams and Pictures.</p>
	  	</div>
  </div>

<% if @current_user %>	
<hr>
	<h2>CURRENT RANKS</h2>
	
	<table class="table table-striped table-hover">
		    <thead>
		        <tr>
		            <th>ID</th>
		            <th>OVERALL RANK</th>
		            <th>NAME</th>
		            <th>ACTIVITITES PREFORMED</th>
		            <th>ACTIVITY LIST</th>
		            <th>TOTAL POINTS</th>
		            <th>COMMENTS</th>
		        </tr>
		    </thead>
			<% @users.each do |user| %>
		    	<tbody >
		  
		     		<tr style="background-color: <%= cycle('rgba(213, 245, 227, 1)', 'rgba(234, 250, 241,.5)') %>">
		            	<td id="uid"><%= user.id %></td>

		            	<td> 
		            		<% @rankings.each do |x| %>
		            			<% if x[0][0] == user.id && x[0][1] != 0 %>
		            				<%= x[1] + 1 %>
		            			<% elsif x[0][0] == user.id && x[0][1] == 0 %>
		            				<%= @zero %>

		            			<% end %>
							<% end %>
		            	</td>

		            	<td> <%= link_to(user.name, user_path(user.id)) %></td> 
		            	
		            	<td><%= Activity.where(:user_id => user.id).count %></td>
		            	
		            	<td>
		            		<ul>
			            		<% if Activity.where(:user_id => user.id).present? %>
			            			<% Activity.where(:user_id => user.id).each do |act|  %>
			            			
			            				<li> <%= link_to(act.activity, activity_path(act)) %> </li>
								
									<% end %>
								<% else %>
										<p>No Activities to report.</p>
			            		<% end %>
		            		</ul>

		            	</td>

		            	<td>
		            		<% if @points_store[user.id] != nil && @points_store[user.id] != 0  %>
			            		<%= @points_store[user.id] %>
			            	<% else %>   
			            		<p>No points to report.</p>
			            	<% end %>
		            	</td>

		            	<td>
		            		<%= Point.where(:activity_user_id => user.id).count %>
		            	</td>

		        	</tr>

		    	</tbody>
		    <% end %>
		</table>
<% end %>	
</div>