config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  get 'signup' => 'users#new'
  resources :users, :points

  #Nested Route - Activities/Points
  resources :activities do
 	  resources :points
  end

  #LOGIN
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #Experimental Graph D3
  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
end

app/models/activity.rb
# == Schema Information
#
# Table name: activities
#
#  id            :integer          not null, primary key
#  activity      :text
#  user_id       :integer
#  created_at    :datetime         not null
#  updated_at    :datetime         not null
#  description   :text
#  created_by_id :integer
#

class Activity < ActiveRecord::Base
	has_many :points, dependent: :destroy
	belongs_to :users

	validates :activity, :presence => true, :uniqueness => true
	validates :description, :presence => true, :length => { :minimum => 3 }
	validates :user_id, :presence => true

	accepts_nested_attributes_for :points, allow_destroy: true


	def total_points()
		total = 0
		
    	self.points.each do |points|
      		total += points.points
    	end

    	total
	end
end

app/controllers/activities_controller.rb
class ActivitiesController < ApplicationController

  before_action :check_if_logged_in, :only => [:index, :edit, :update, :show, :new, :destroy]
  before_action :check_activity_owner, :only => [:edit, :update]

  def index
  	@activities = Activity.all
  	@users = User.all
    @points = Point.all

    @current_user_activities = @current_user.activities
  end

  def show
  	@activity = Activity.find params[:id]
  
    #Get Total Points for Activity
    @total = 0

    @activity.points.each do |points|
      @total += points.points
    end

  end

  def new
    @activity = Activity.new
  end

  def create
    @activity = Activity.create activity_params
    
    if @activity.save # Check if the user is valid (per the validations in the model)
      redirect_to activity_path(@activity)
    else
      render :new
    end
    
  end

  def edit
    @activity = Activity.find params[:id]
    @current_user = User.find(session[:user_id])
  end

  def update
    activity = Activity.find params[:id]
    activity.update activity_params

    redirect_to activity
  end

  def destroy
    activity = Activity.find params[:id]
    activity.destroy
    
    redirect_to activities_path
  end

  private

  def activity_params
    params.require(:activity).permit(:activity, :user_id, :description, :created_by_id)
  end

  def check_if_logged_in
    redirect_to root_path unless @current_user.present?
  end

  def check_activity_owner
    # check if current user created activity
     redirect_to root_path unless @current_user.present? && Activity.find(params[:id]).created_by_id == @current_user.id || @current_user.admin?
  end

end

app/helpers/activities_helper.rb
module ActivitiesHelper
end

app/views/activities/_form.html.erb
<div class="new">


<% if @activity.errors.any? %>
  <ol>
    <% @activity.errors.full_messages.each do |msg| %>
      <li id="errors">
        <%= msg %>
      </li>
    <% end %>
  </ol>
<% end %>

<%= form_for(@activity) do |f| %>
	<p>
		<%= f.label :activity %>
		<%= f.text_field :activity, :class => 'form-control' %>
	</p>
	<p>
		<%= f.label :description %>
		<%= f.text_area :description, size: "40x6", :class => 'form-control' %>
	</p>
	<p>
	Who did this? : <%= f.select :user_id, User.all.map { |user| [user.name,  user.id] }, {}, :class => 'form-control', :include_blank => true %>
	</p>
	<p>Who are you? : <%= f.select :created_by_id, [[@current_user.name,  @current_user.id]], {}, :class => 'form-control' %></p>


	<%= f.submit 'Submit Activity', :class => "btn btn-primary" %>
<% end %>

</div>

app/views/activities/edit.html.erb
<h2>UPDATE ACTIVITY</h2>

<%= render :partial => 'form' %>

app/views/activities/index.html.erb
<h2>Your Activities List</h2>
	<hr>

<% if @current_user_activities.present? %>
	<p class="thepad"><%= @current_user.name %>, here are all your activities.</p>
	<% @current_user_activities.each do |activity| %>
	
		<h4 style="background-color: <%= cycle('rgba(213, 245, 227, 1)', 'rgba(234, 250, 241,.5)') %>" class="thepad"><i class="fa fa-star-o"></i> Activity: <%= activity.activity %> || <%= link_to('View Stats', activity_path(activity)) %>
		Total Points: <%= activity.total_points %>
		</h4>
		
	<% end %>
	<hr>
<% else %>

	<p class="thepad"><%= @current_user.name %>, looks like you haven't done any activities yet. Add them yourself or have the others add them for you.</p>
<% end %>

<div class="other_activities">
	<h2>Other User Activities List</h2>
	
	<hr>

	<p class="thepad">Add some feedback to the activities.</p>

	<% @activities.each do |activity| %>

		<% if User.exists?(activity.user_id) && User.find(activity.user_id).id != @current_user.id   %>

			<p style="background-color: <%= cycle('rgba(213, 245, 227, 1)', 'rgba(234, 250, 241,.5)') %>" class="thepad" >User: <%= link_to(User.find(activity.user_id).name, activity_path(activity)) %> || 
			Activity: <%= activity.activity %>
			<%= link_to('View Stats', activity_path(activity)) %> | 
			<i class="fa fa-comment-o"></i> <%= link_to('Give Feedback', new_activity_point_path(activity, @point)) %> 
			</p>
		
		<% end %>	
		
	<% end %>

</div>

app/views/activities/new.html.erb
<h2>NEW ACTIVITY</h2>

<%= render :partial => 'form' %>

app/views/activities/show.html.erb
<h2>Activity: <%= @activity.activity %></h2>
<hr>

<p>Person who preformed activity: <%= User.find(@activity.user_id).name %></p>
<p>Description: <%= @activity.description %></p>
<p>TOTAL POINTS: <%= @total %>/<%= @activity.points.count * 10 %></p>

<h3>Voting Users </h3>
<hr>

<div class="controls">
	<% if @current_user.id == @activity.created_by_id || @current_user.admin?%>
		<%= link_to 'Edit', edit_activity_path(@activity) %>
	<% end %>
	
	<% if @current_user.admin? %>
		<%= link_to "Delete", @activity, :method => 'delete', data: {confirm: 'Are you sure?'} %>
	<% end %>

	<% if @current_user.id != @activity.user_id %>
		<%= link_to "ADD FEEDBACK",  new_activity_point_path(@activity, @point) %> <i class="fa fa-comment-o"></i>
	<% end %>
	<% if User.exists?(@activity.created_by_id) %>
		Activity was Created by: <%= User.find(@activity.created_by_id).name %>
	<% else %>
		The user that created this has been removed.
	<% end %>
</div>
<hr>
	<% @activity.points.each do |x| %>
		<div style="background-color: <%= cycle('rgba(213, 245, 227, 1)', 'rgba(234, 250, 241,.5)') %>" class="thepad">
			<h4><i class="fa fa-angle-double-right"></i> <%= User.find(x.voting_user_id).name %> gave you <%= pluralize(x.points, '/ 10 Point') %></h4> 
		<div class="comment">

		<h4>Comment/Feedback</h4> 
			<% if x.comment.present? %>
				<pre> <%= x.comment %></pre> 
			<% else %>
				<pre>No comment here.</pre>
			<% end %>
		</div>
		</div>
		
	<% end %>

<hr>