config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  get 'signup' => 'users#new'
  resources :users, :points

  #Nested Route - Activities/Points
  resources :activities do
 	  resources :points
  end

  #LOGIN
  get '/login' => 'session#new'
  post '/login' => 'session#create'
  delete '/login' => 'session#destroy'

  #Experimental Graph D3
  get 'graph/index'
  get 'graph/data', :defaults => { :format => 'json' }
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Karmapolice</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.4.0/css/font-awesome.min.css">
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

	<nav class="navbar navbar-default">
  <div class="container-fluid">
    <!-- Brand and toggle get grouped for better mobile display -->
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand deadlink" href="#">Karma Police</a>
    </div>

    <!-- Collect the nav links, forms, and other content for toggling -->
    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
      <ul class="nav navbar-nav">
        <% if @current_user && @current_user.admin? %> 
			<li class="deadlink"><%= link_to 'ADMIN', user_path(@current_user) %></li>
			<li><%= link_to 'USERS', users_path %> </li>			 
		<% end %>
	
		<% if @current_user %> 
		  	<li class="deadlink" id="welcome"><%= link_to "Welcome #{@current_user.name}", user_path(@current_user) %> </li>	 
		  	<li><%= link_to( '', root_path, :class => "fa fa-home fa-lg") %></li>
		   	<li><%= link_to 'Profile', user_path(@current_user) %></li>
		   	<li><%= link_to 'Activities', activities_path %></li>
		    <li><%= link_to 'Create New Activity', new_activity_path %></li>
		    <li><%= link_to "Logout #{ @current_user.name }", login_path, :method => 'delete', :data => { :confirm => 'Are you sure you wish to logout?' } %> </li>
		   
		<% else %> 
		  	
		    <li><%= link_to "Login", login_path %></a></li> 
		    <li><%= link_to( '', root_path, :class => "fa fa-home fa-lg") %></li>
		    <li><%= link_to "Signup", signup_path %></a></li> 
		    
		<% end %>
    
      </ul>
    </div><!-- /.navbar-collapse -->
  </div><!-- /.container-fluid -->
</nav>

	
	<div class="container">

		<% if flash[:message].present? %>
  			<p id="errors"><%= flash[:message] %></p>
		<% end %>
		
		<%= yield %>
	</div>

	<footer class="footer"><p>Karma Po Po // a peer based feedback system.<span>...</span></p> </footer>

</body>
</html>